language: java

script: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
after_script: mvn test

cache:
  directories:
  - .autoconf
  - $HOME/.m2

notifications:
  email:
    - irfani.angela@gmail.com