language: java
jdk:
- oraclejdk8

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn test

cache:
  directories:
  - .autoconf
  - $HOME/.m2

notifications:
  email:
    - irfani.angela@gmail.com