language: java
jdk:
- oraclejdk8

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn test

deploy:
  provider: heroku
  api_key:
    secure: 31db7e93abceef03af7db5914e8b66d9
  app:
    master: rmsbackendspring
    dev: rmsbackendspringstaging

cache:
  directories:
  - .autoconf
  - $HOME/.m2

notifications:
  email:
    - irfani.angela@gmail.com